### ISSUE TITLE
[Wont happen] Onboarding process rOpenSci

### ISSUE THREAD

**Issue by dmpe** [dmpe/urlshorteneR#3]
Prepare for filing an issue https://github.com/ropensci/onboarding/issues
- [ ] https://github.com/ropensci/onboarding/blob/master/CONTRIBUTING.md
- [x] https://github.com/ropensci/packaging_guide
- [ ] https://github.com/ropensci/policies 
## 
- [x] Tested on Linux Ubuntu 14.04 and Win.10 with R PRO (now $MSFT)
- [x] Naming convections should now be OK
- [x] tests, travis, docs - are all added.
## 
- [x] Need to fix/rethink/modify how I create URL to download json data. See https://github.com/hadley/httr/blob/master/vignettes/quickstart.Rmd#the-request
## 

Bugs:
- [x] #5

**Comment by karthik** [comment]
I'll work with you on this part so that we can make the ropensci end as smooth and quick as possible.

**Comment by dmpe** [comment]
Hi, Great. 
I have already prepared vignette. Yet there is still some things to do e.g. :
`We strongly recommend snake_case over all other styles unless you are porting over a package that is already in wide use. ` which however I have missed so that now I will need to replace it.

**Comment by karthik** [comment]
No worries. I'm currently traveling with poor internet but please assign any tasks to which I can contribute. I'll take a look at open issues shortly.

**Comment by dmpe** [comment]
@karthik From the beggining I have followed this way:

1. Create a JSON URL with all (user's) input parameters [e.g. created_URL](https://github.com/dmpe/rbitly/blob/master/R/UserInfo.R#L108). 

2. Then pass that URL to [doRequest function](https://github.com/dmpe/rbitly/blob/master/R/ApiKey.R#L68) which will download and return the content to the former function. That content is modified and returned to the user. 

However, this is inconvenient/problematic + less extensible. To summarize, a "architectural **mistake**".
 
This can be, very naturally, accomplished by (example borrowed from @ hadley's httr which I didn't study good enough - even though I also use)

```
r <- GET("http://httpbin.org/get", 
  query = list(key1 = "value1", key2 = "value2")
)
```

Now, it will take some time for me to implement it. Therefore, if you don't hurry up to publish it on CRAN (or move to rOpenSci) early, then I would take some time (1-2 weeks from now) to do it. Thus I want it to be really ready when it is going to move to CRAN/rOpenSci.

**Comment by dmpe** [comment]
Fixing in 
https://github.com/dmpe/rbitly/commit/c697022a736874bd0b8b1f7a815d141635082c93
https://github.com/dmpe/rbitly/commit/314cbaec5c951c422aae3c7877531bc43f067bde

**Comment by dmpe** [comment]
Hi @karthik, 

So far so good. At this stage I am finished (most probably) with my own requirenments in order to file an transfer issue at rOpenSci. One last question.  

Before I am going to file an issue for onboarding I just wanted to ask if I am also going to recieve a "direct" push access if the package will be accepted (e.g. same as I have given to you and Hadley ?).
Thanks for your answer because I could not find that explicitly.

**Comment by karthik** [comment]
Hi @dmpe 
Mind if I do some code review here before we get to onboarding? I'll contribute at least a better auth function. 

> Before I am going to file an issue for onboarding I just wanted to ask if I am also going to recieve a "direct" push access if the package will be accepted (e.g. same as I have given to you and Hadley ?).

Yes, you'll be added to a team with direct push access to project that you collaborate on. And everything else, including authorship will remain the same as it is here.

**Comment by dmpe** [comment]
Great. 
Oh, course @karthik . Feel free to do what you see/think is necessary. I haven't assigned you any bug because I didn't know what to should I assign.

**Comment by dmpe** [comment]
Hi @karthik , 
I checked other packages which use some kind of API at rOpenSci and saw for example :
https://github.com/ropensci/rnoaa/blob/master/R/zzz.r#L183
```
check_key <- function(x){
  tmp <- if(is.null(x)) Sys.getenv("NOAA_KEY", "") else x
  if(tmp == "") getOption("noaakey", stop("need an API key for NOAA data")) else tmp
}
```
Or something like: https://github.com/ropensci/gistr/blob/master/R/gist_auth.R#L24

Is that what you have meant ? I neither opposed nor in favour of this. :wink:

**Comment by dmpe** [comment]
At the moment, I will leave this open. But per discussion there will not be any onboarding.
